name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        os-version: ["ubuntu-latest", "windows-latest"]
        node-version: [14, 16, 18]
    name: Build
    runs-on: ${{matrix.os-version}}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Check Lnt
        run: npm run lint
      - name: Check Prettier
        run: npm run prettier
      - name: Build
        run: npm run build
